name: o_color_picker_example
description: o_color_picker example app
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  o_color_picker:
    path: ../
  cupertino_icons: ^0.1.3
  o_popup: ^0.1.2

flutter:
  uses-material-design: true
