name: o_color_picker
description: Simple and fast 2-step color picker, which supports shades and colors customization.
version: 1.0.2
homepage: https://github.com/owczaro/o_color_picker
issue_tracker: https://github.com/owczaro/o_color_picker/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
